use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::source_package::{self, EntryContent, EntryKind, InputEntry};
use crate::ustar;

const VECTORS: &str = include_str!("../contracts/source-package/v1/vectors.json");
static NONCE: AtomicU64 = AtomicU64::new(0);

#[derive(Deserialize)]
struct Vectors {
    version: u8,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    valid: bool,
    error: Option<String>,
    entries: Vec<VectorEntry>,
    #[serde(default)]
    generate: Vec<Generate>,
    sha256: Option<String>,
}

#[derive(Deserialize)]
struct VectorEntry {
    path: String,
    #[serde(rename = "type")]
    kind: String,
    text: Option<String>,
    base64: Option<String>,
    repeat: Option<Repeat>,
}

#[derive(Deserialize)]
struct Repeat {
    byte: String,
    count: usize,
}

#[derive(Deserialize)]
struct Generate {
    root: String,
    prefix: String,
    suffix: String,
    start: usize,
    count: usize,
    width: usize,
    text: String,
}

struct TemporaryDirectory {
    path: PathBuf,
}

impl TemporaryDirectory {
    fn new() -> Self {
        let nonce = NONCE.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "shimpz-source-package-{}-{nonce}",
            std::process::id()
        ));
        fs::create_dir(&path).expect("temporary directory");
        Self { path }
    }
}

impl Drop for TemporaryDirectory {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.path).expect("remove temporary directory");
    }
}

#[test]
fn matches_every_source_package_golden_vector() {
    let vectors: Vectors = serde_json::from_str(VECTORS).expect("valid vectors");
    assert_eq!(vectors.version, 1);
    for case in vectors.cases {
        let entries = vector_entries(&case);
        let result = ustar::build(&entries);
        if case.valid {
            let bytes = result.unwrap_or_else(|error| panic!("{}: {error}", case.name));
            assert_eq!(
                format!("{:x}", Sha256::digest(bytes)),
                case.sha256.expect("valid digest"),
                "{}",
                case.name
            );
        } else {
            assert_eq!(
                result.expect_err(&case.name).code(),
                case.error.as_deref().expect("negative error"),
                "{}",
                case.name
            );
        }
    }
}

#[test]
fn collects_only_publishable_roots_from_disk() {
    let temporary = TemporaryDirectory::new();
    write_minimum(&temporary.path);
    fs::write(temporary.path.join("README.md"), "Local notes.\n").expect("README");

    let package = source_package::build(&temporary.path).expect("source package");

    assert_eq!(
        package.digest,
        "sha256:393136771c3bfb110a06aa852aebe7a23084ed4a6c3abb0c27a81cd967bebf5b"
    );
    assert_eq!(package.excluded_roots, ["README.md"]);
    assert_eq!(package.manifest, b"spec = 1\n");
    assert_eq!(package.bytes.len() % 512, 0);
    assert_eq!(
        source_package::exclusion_warning(&package).as_deref(),
        Some("Excluded from publish: \"README.md\"")
    );
    assert!(!source_package::check_summary(&package).contains("Excluded"));
}

#[test]
fn collects_only_direct_python_files_from_powers() {
    let temporary = TemporaryDirectory::new();
    write_minimum(&temporary.path);
    let expected = source_package::build(&temporary.path).expect("baseline source package");
    let powers = temporary.path.join("powers");
    fs::write(powers.join("README.md"), "Local notes.\n").expect("Power notes");
    fs::write(powers.join("hello.py.bak"), "backup\n").expect("Power backup");
    fs::create_dir(powers.join("__pycache__")).expect("Python cache");
    fs::write(
        powers.join("__pycache__/hello.cpython-314.pyc"),
        "generated bytecode",
    )
    .expect("cached bytecode");
    fs::create_dir(powers.join("drafts")).expect("draft directory");
    fs::write(powers.join("drafts/nested.py"), "not a Power\n").expect("nested draft");

    let actual = source_package::build(&temporary.path).expect("filtered source package");

    assert_eq!(actual.digest, expected.digest);
    assert_eq!(actual.bytes, expected.bytes);
}

#[cfg(unix)]
#[test]
fn rejects_a_python_symlink_inside_powers() {
    use std::os::unix::fs::symlink;

    let temporary = TemporaryDirectory::new();
    write_minimum(&temporary.path);
    symlink(
        temporary.path.join("outside.py"),
        temporary.path.join("powers/link.py"),
    )
    .expect("Power symlink");

    let error = source_package::build(&temporary.path)
        .err()
        .expect("Power symlink must fail");

    assert_eq!(error, "source package is invalid: special_file");
}

#[test]
fn rejects_hardlinks_inside_publishable_roots() {
    let temporary = TemporaryDirectory::new();
    write_minimum(&temporary.path);
    let original = temporary.path.join("outside.py");
    fs::write(&original, "VALUE = 1\n").expect("original");
    fs::hard_link(&original, temporary.path.join("powers/alias.py")).expect("hardlink");

    let error = source_package::build(&temporary.path)
        .err()
        .expect("hardlink must fail");

    #[cfg(unix)]
    assert_eq!(error, "source package is invalid: special_file");
    #[cfg(windows)]
    assert_eq!(error, "source package is invalid: invalid_entry");
}

#[cfg(unix)]
#[test]
fn rejects_symlinks_inside_publishable_roots() {
    use std::os::unix::fs::symlink;

    let temporary = TemporaryDirectory::new();
    write_minimum(&temporary.path);
    fs::create_dir(temporary.path.join("lib")).expect("lib");
    symlink(
        temporary.path.join("outside.py"),
        temporary.path.join("lib/link.py"),
    )
    .expect("symlink");

    let error = source_package::build(&temporary.path)
        .err()
        .expect("symlink must fail");

    assert_eq!(error, "source package is invalid: special_file");
}

fn write_minimum(root: &Path) {
    fs::create_dir(root.join("powers")).expect("powers");
    fs::write(root.join("shimpz.toml"), "spec = 1\n").expect("manifest");
    fs::write(root.join("icon.png"), valid_icon()).expect("icon");
    fs::write(root.join("pyproject.toml"), "[project]\nname = \"hello\"\n").expect("project");
    fs::write(
        root.join("powers/hello.py"),
        "async def run():\n    return \"hello\"\n",
    )
    .expect("Power");
}

fn vector_entries(case: &Case) -> Vec<InputEntry> {
    let mut entries = case.entries.iter().map(vector_entry).collect::<Vec<_>>();
    for generate in &case.generate {
        for index in generate.start..generate.start + generate.count {
            entries.push(InputEntry {
                path: format!(
                    "{}/{}{:0width$}{}",
                    generate.root,
                    generate.prefix,
                    index,
                    generate.suffix,
                    width = generate.width
                ),
                kind: EntryKind::RegularFile,
                content: EntryContent::Bytes(generate.text.as_bytes().to_vec()),
            });
        }
    }
    entries
}

fn vector_entry(entry: &VectorEntry) -> InputEntry {
    let kind = if entry.kind == "regular_file" {
        EntryKind::RegularFile
    } else {
        EntryKind::Special
    };
    let bytes = entry.repeat.as_ref().map_or_else(
        || {
            entry.base64.as_ref().map_or_else(
                || {
                    entry
                        .text
                        .as_deref()
                        .unwrap_or_default()
                        .as_bytes()
                        .to_vec()
                },
                |encoded| BASE64.decode(encoded).expect("valid vector base64"),
            )
        },
        |repeat| repeat.byte.as_bytes().repeat(repeat.count),
    );
    InputEntry {
        path: entry.path.clone(),
        kind,
        content: EntryContent::Bytes(bytes),
    }
}

fn valid_icon() -> Vec<u8> {
    let vectors: Vectors = serde_json::from_str(VECTORS).expect("valid vectors");
    let encoded = vectors.cases[0].entries[0]
        .base64
        .as_ref()
        .expect("canonical icon vector");
    BASE64.decode(encoded).expect("valid canonical icon")
}
